# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20151117_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='ordering',
            field=models.PositiveSmallIntegerField(verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='column',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Row', verbose_name='Row'),
        ),
        migrations.AlterField(
            model_name='gridobject',
            name='Content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='gridobject',
            name='Title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gridobject',
            name='horizontalPosition',
            field=models.IntegerField(default=0, verbose_name='HorizontalPosition'),
        ),
        migrations.AlterField(
            model_name='gridobject',
            name='horizontalSize',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six'), (7, 'seven'), (8, 'eight'), (9, 'nine'), (10, 'ten'), (11, 'eleven'), (12, 'twelve'), (13, 'thirteen'), (14, 'fourteen'), (15, 'fifteen'), (16, 'sixteen')], default=1, verbose_name='HorizontalSize'),
        ),
        migrations.AlterField(
            model_name='gridobject',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='gridobject',
            name='verticalPosition',
            field=models.IntegerField(default=0, verbose_name='VerticalPosition'),
        ),
        migrations.AlterField(
            model_name='gridobject',
            name='verticalSize',
            field=models.IntegerField(default=1, verbose_name='VerticalSize'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='ordering',
            field=models.PositiveSmallIntegerField(verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sidebar_right',
            field=models.BooleanField(default=True, verbose_name='Sidebar right?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slogan',
            field=models.CharField(max_length=255, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pagearticle',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pagearticle',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pagearticle',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pagefacebooklink',
            name='link',
            field=models.TextField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='pagefacebooklink',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pagefacebooklink',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pagefaq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='pagefaq',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='pagefaq',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pagefile',
            name='file',
            field=smartfields.fields.FileField(upload_to='files/%Y/%m/%d', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='pagefile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pagefile',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pageform',
            name='message',
            field=smartfields.fields.TextField(verbose_name='Thank you message'),
        ),
        migrations.AlterField(
            model_name='pageform',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pageformelement',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.PageForm', verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='pageformelement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Element name'),
        ),
        migrations.AlterField(
            model_name='pageformelement',
            name='required',
            field=models.BooleanField(verbose_name='Required?'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='link',
            field=models.TextField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pagephoto',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pagephoto',
            name='photo',
            field=smartfields.fields.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='pagephoto',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pageyoutubelink',
            name='link',
            field=models.TextField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='pageyoutubelink',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='pageyoutubelink',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='row',
            name='ordering',
            field=models.PositiveSmallIntegerField(verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='row',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page'),
        ),
    ]
