from django.conf.urls import url
from django.contrib.auth import views as auth_views
from demo_site.pages import views

urlpatterns = [
    # Test stuff
    url(r'^grid/$', views.PageGrid.as_view(), name='grid'),
    url(r'^grid/new/$', views.PageGridCreate.as_view(), name='grid-new'),
    url(r'^grid/edit/(?P<pk>\d+)$', views.PageGridUpdate.as_view(), name='grid-edit'),
    url(r'^grid/delete/(?P<pk>\d+)$', views.PageGridDelete.as_view(), name='grid-delete'),

    # Real stuff
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    # url(r'^row/add/(?P<page_url>[-\w\d]+)/', views.RowAddView, name='row-add'),
    # url(r'^row/delete/(?P<page_url>[-\w\d]+)/(?P<row_id>[\d]+)/', views.RowDeleteView, name='row-delete'),
    # url(r'^row/sortable/', views.RowSortableView, name='row-sortable'),
    # url(r'^column/add/(?P<page_url>[-\w\d]+)/(?P<row_id>[\d]+)/', views.ColumnAddView, name='column-add'),
    # url(r'^column/delete/(?P<page_url>[-\w\d]+)/(?P<row_id>[\d]+)/(?P<column_id>[\d]+)/', views.ColumnDeleteView,
    #     name='column-delete'),
    # url(r'^column/sortable/', views.ColumnSortableView, name='column-sortable'),
    # url(r'^content/save/$', views.ContentSaveView, name='content-save'),
    # url(r'^item/add/(?P<page_url>[-\w\d]+)/(?P<colomn_id>[\d]+)/(?P<content_type>[\w\d]+)/', views.ItemAddView,
    #     name='item-add'),
    # url(r'^item/remove/(?P<page_url>[-\w\d]+)/(?P<colomn_id>[\d]+)/(?P<content_type>[\w\d]+)/(?P<object_id>[\d]+)/',
    #     views.ItemRemoveView, name='item-remove'),
    # url(r'^cms/', views.CMSIndexView, name='cms'),
    # url(r'^pages/sortable/', views.PageSortableView, name='pages-sortable'),
    # url(r'^pages/(?P<parent>[\d]+)/', views.PagesView, name='pages-parent'),
    # url(r'^pages/', views.PagesView, name='pages'),
    # url(r'^forms/$', views.FormsView, name='forms'),
    # url(r'^photos/$', views.PhotosView, name='photos'),
    # url(r'^photo/add/$', views.PhotoAddView, name='photo-add'),
    # url(r'^photo/browser/$', views.PhotoBrowserView, name='photo-browser'),
    # url(r'^photo/uploader/$', views.PhotoUploadView, name='photo-uploader'),
    # url(r'^files/$', views.FilesView, name='files'),
    # url(r'^file/add/$', views.FileAddView, name='file-add'),
    # url(r'^file/browser/$', views.FileBrowserView, name='file-browser'),
    # url(r'^file/uploader/$', views.FileUploadView, name='file-uploader'),

    url(r'^page$', views.PageList.as_view(), name='page-list'),
    url(r'^page/new/', views.PageListCreate.as_view(), name='page-new'),
    url(r'^page/edit/(?P<pk>\d+)$', views.PageUpdate.as_view(), name='page-edit'),
    url(r'^page/delete/(?P<pk>\d+)$', views.PageDelete.as_view(),name='page-delete'),


    url(r'^article$', views.PageArticleList.as_view(), name='article-list'),
    url(r'^article/(?P<pk>\d+)$', views.PageArticleDetail.as_view(), name='article-detail'),
    url(r'^article/new$', views.PageArticleCreate.as_view(), name='article-new'),
    url(r'^article/edit/(?P<pk>\d+)$', views.PageArticleUpdate.as_view(), name='article-edit'),
    url(r'^article/delete/(?P<pk>\d+)$', views.PageArticleDelete.as_view(), name='article-delete'),
    url(r'^faq$', views.PageFAQList.as_view(), name='faq-list'),
    url(r'^faq/(?P<pk>\d+)$', views.PageFAQDetail.as_view(), name='faq-detail'),
    url(r'^faq/new$', views.PageFAQCreate.as_view(), name='faq-new'),
    url(r'^faq/edit/(?P<pk>\d+)$', views.PageFAQUpdate.as_view(), name='faq-edit'),
    url(r'^faq/delete/(?P<pk>\d+)$', views.PageFAQDelete.as_view(), name='faq-delete'),
    url(r'^link$', views.PageLinkList.as_view(), name='link-list'),
    url(r'^link/(?P<pk>\d+)$', views.PageLinkDetail.as_view(), name='link-detail'),
    url(r'^link/new$', views.PageLinkCreate.as_view(), name='link-new'),
    url(r'^link/edit/(?P<pk>\d+)$', views.PageLinkUpdate.as_view(), name='link-edit'),
    url(r'^link/delete/(?P<pk>\d+)$', views.PageLinkDelete.as_view(), name='link-delete'),
    url(r'^youtubelink$', views.PageYoutubeLinkList.as_view(), name='youtubelink-list'),
    url(r'^youtubelink/(?P<pk>\d+)$', views.PageYoutubeLinkDetail.as_view(), name='youtubelink-detail'),
    url(r'^youtubelink/new$', views.PageYoutubeLinkCreate.as_view(), name='youtubelink-new'),
    url(r'^youtubelink/edit/(?P<pk>\d+)$', views.PageYoutubeLinkUpdate.as_view(), name='youtubelink-edit'),
    url(r'^youtubelink/delete/(?P<pk>\d+)$', views.PageYoutubeLinkDelete.as_view(),
        name='youtubelink-delete'),
    url(r'^facebooklink$', views.PageFacebookLinkList.as_view(), name='facebooklink-list'),
    url(r'^facebooklink/(?P<pk>\d+)$', views.PageFacebookLinkDetail.as_view(), name='facebooklink-detail'),
    url(r'^facebooklink/new$', views.PageFacebookLinkCreate.as_view(), name='facebooklink-new'),
    url(r'^facebooklink/edit/(?P<pk>\d+)$', views.PageFacebookLinkUpdate.as_view(), name='facebooklink-edit'),
    url(r'^facebooklink/delete/(?P<pk>\d+)$', views.PageFacebookLinkDelete.as_view(),
        name='facebooklink-delete'),
    url(r'^(?P<slug>[-\w\d]+)$', views.PageView, name='page'),
    url(r'^', views.IndexView, name='default'),
]
